/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as LineupFestivalStageImport } from './routes/lineup/$festival/$stage'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const LineupFestivalStageRoute = LineupFestivalStageImport.update({
  path: '/lineup/$festival/$stage',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/lineup/$festival/$stage': {
      id: '/lineup/$festival/$stage'
      path: '/lineup/$festival/$stage'
      fullPath: '/lineup/$festival/$stage'
      preLoaderRoute: typeof LineupFestivalStageImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  LineupFestivalStageRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.ts",
      "children": [
        "/",
        "/lineup/$festival/$stage"
      ]
    },
    "/": {
      "filePath": "index.ts"
    },
    "/lineup/$festival/$stage": {
      "filePath": "lineup/$festival/$stage.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
